# Generated by Django 2.1.7 on 2021-07-20 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_nm', models.CharField(max_length=20)),
                ('street_nm', models.CharField(max_length=20)),
                ('city_nm', models.CharField(max_length=20)),
                ('state_nm', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.UserProfile')),
            ],
        ),
    ]
